### ISSUE TITLE
Unexpected element type com.datastax.spark.connector.japi.CassandraRow

### ISSUE THREAD

**Issue by frensjan** [Parsely/pyspark-cassandra#2]
Hi,

I'm trying to use pyspark-cassandra, but an exception is raised in org.apache.spark.api.python.PythonRDD.writeIteratorToStream(...) with the message 'Unexpected element type com.datastax.spark.connector.japi.CassandraRow'. I can use Spark and Cassandra through the datastax connector in Scala just fine, but python compatibility would be very nice. Any suggestions?

My versions are:
- cassandra-driver-core-2.1.4
- spark-cassandra-connector-java_2.10-1.2.1
- spark-core_2.10-1.2.0

Thanks,
Frens Jan

**Comment by dfdeshom** [comment]
@frensjan do you have an example of the code you're trying to use that throws the exception?

**Comment by frensjan** [comment]
@dfdeshom, the most basic code which reproduces this is something along the lines of:

``` python
import os

from py4j.java_gateway import java_import
from pyspark.context import SparkConf
from pyspark.context import SparkContext
from pyspark.rdd import RDD
from pyspark.serializers import BatchedSerializer, PickleSerializer

class CassandraSparkContext(SparkContext):

    def _do_init(self, *args, **kwargs):
        super(CassandraSparkContext, self)._do_init(*args, **kwargs)
        java_import(self._jvm, "com.datastax.spark.connector.japi.CassandraJavaUtil")
        self._jcsc = self._jvm.CassandraJavaUtil.javaFunctions(self._jsc)

    def cassandraTable(self, keyspace, table):
        return RDD(self._jcsc.cassandraTable(keyspace, table), self, BatchedSerializer(PickleSerializer()))


conf = SparkConf().setAppName("PySpark Cassandra Test")
conf.setMaster("spark://spark-master:7077")
conf.set("spark.cassandra.connection.host", "cas-1")
sc = CassandraSparkContext(conf=conf)

print(sc.cassandraTable('tmp', 'tbl', ).first())
```

As you can see I concocted a mix of pyspark_cassandra.py and some client code ... making it a little bit easer to test and debug.

The most relevant logging is shown below. These errors are raised on every node which reads a cql row from Cassandra.

```
15/02/18 08:37:22 INFO DAGScheduler: Job 0 failed: runJob at PythonRDD.scala:344, took 4.330056 s
Traceback (most recent call last):
  File "/home/frens-jan/Desktop/test.py", line 25, in <module>
    print(sc.cassandraTable('tmp', 'tbl', ).first())
  File "/home/frens-jan/.m2/repository/org/apache/spark/spark-core_2.10/1.2.0/spark-core_2.10-1.2.0.jar/pyspark/rdd.py", line 1129, in first
  File "/home/frens-jan/.m2/repository/org/apache/spark/spark-core_2.10/1.2.0/spark-core_2.10-1.2.0.jar/pyspark/rdd.py", line 1111, in take
  File "/home/frens-jan/.m2/repository/org/apache/spark/spark-core_2.10/1.2.0/spark-core_2.10-1.2.0.jar/pyspark/context.py", line 818, in runJob
  File "/home/frens-jan/.m2/repository/org/apache/spark/spark-core_2.10/1.2.0/spark-core_2.10-1.2.0.jar/py4j/java_gateway.py", line 538, in __call__
  File "/home/frens-jan/.m2/repository/org/apache/spark/spark-core_2.10/1.2.0/spark-core_2.10-1.2.0.jar/py4j/protocol.py", line 300, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.runJob.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3, cas-3): org.apache.spark.SparkException: Unexpected element type class com.datastax.spark.connector.japi.CassandraRow
    at org.apache.spark.api.python.PythonRDD$.writeIteratorToStream(PythonRDD.scala:420)
    at org.apache.spark.api.python.PythonRDD$WriterThread$$anonfun$run$1.apply$mcV$sp(PythonRDD.scala:242)
    at org.apache.spark.api.python.PythonRDD$WriterThread$$anonfun$run$1.apply(PythonRDD.scala:204)
    at org.apache.spark.api.python.PythonRDD$WriterThread$$anonfun$run$1.apply(PythonRDD.scala:204)
    at org.apache.spark.util.Utils$.logUncaughtExceptions(Utils.scala:1468)
    at org.apache.spark.api.python.PythonRDD$WriterThread.run(PythonRDD.scala:203)
```

Note that I have found a way around this by implementing a custom `com.datastax.spark.connector.rdd.reader.RowReader` which converts the `com.datastax.driver.core.Row` to a `java.util.Map` which is subsequently pickled using `net.razorvine.pickle.Pickler`. Let's just say that it works ... but maybe not the prettiest solution out there ...
